title: Tahrovin Wiki
description: A getting Started Wiki for the Tahrovin Wabbajack list.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

logo: "img\Tahrovin.png"

color_scheme: dark