title: Tahrovin Wiki
description: A getting Started Wiki for the Tahrovin Wabbajack list.
theme: just-the-docs
color_scheme: dark
# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true
logo: "/assets/images/Tahrovin.png"

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

url: https://neochiken.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

heading_anchors: true
